name: Lint Markdown

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - run: npm install -g markdownlint-cli@0.27.1
      - run: markdownlint '**/*.md' --ignore node_modules
